# Generated by Django 4.2.30 on 2026-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chatmessage_options_chatsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
        migrations.DeleteModel(
            name='StudentNote',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
        migrations.DeleteModel(
            name='UserMedia',
        ),
    ]
