# Generated by Django 4.2.30 on 2026-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_referral_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='exercise_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Explicit exercise/question reference (e.g. '7.3' or '7.3#2'). Hard cache-scope key.", max_length=20),
        ),
        migrations.AddField(
            model_name='semanticanswercache',
            name='exercise_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Explicit exercise/question reference (e.g. '7.3' or '7.3#2'). Hard cache-scope key.", max_length=20),
        ),
    ]
