# Generated by Django 4.2.30 on 2026-09-15 15:16

from django.db import migrations, models


def backfill_session_chapters(apps, schema_editor):
    """Backfill ChatSession.chapter from message history.

    Only trusts a message's chapter when that message's context subject
    matches the session's subject — messages saved during the stale-state
    bug (wrong subject's chapter in another subject's session) are skipped.
    """
    ChatSession = apps.get_model('api', 'ChatSession')
    ChatMessage = apps.get_model('api', 'ChatMessage')

    for session in ChatSession.objects.all().iterator():
        if (session.chapter or '').strip():
            continue
        subject = (session.subject or '').strip()
        if not subject:
            continue
        chapter = ''
        for message in (
            ChatMessage.objects
            .filter(session_id=session.id)
            .order_by('-created_at')
            .only('context')
            .iterator()
        ):
            message_context = message.context or {}
            if (
                str(message_context.get('subject') or '').strip() == subject
                and str(message_context.get('chapter') or '').strip()
            ):
                chapter = str(message_context['chapter']).strip()[:255]
                break
        if chapter:
            session.chapter = chapter
            session.save(update_fields=['chapter'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_knowledgebaseentry_exercise_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='chapter',
            field=models.CharField(blank=True, default='', help_text='Latest chapter selected in this session. Authoritative for context restore.', max_length=255),
        ),
        migrations.RunPython(backfill_session_chapters, migrations.RunPython.noop),
    ]
