# Generated by Django 4.2.30 on 2026-09-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('daily_window_start', models.DateTimeField(blank=True, null=True)),
                ('daily_limit_reached_at', models.DateTimeField(blank=True, help_text='Set when the daily quota is used up; blocks until +24h.', null=True)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('monthly_window_start', models.DateTimeField(blank=True, null=True)),
                ('monthly_limit_reached_at', models.DateTimeField(blank=True, help_text='Set when the monthly quota is used up; blocks until +30d.', null=True)),
                ('minute_count', models.PositiveIntegerField(default=0)),
                ('minute_window_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
