# Generated by Django 4.2.30 on 2026-10-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usagecounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
